import { TFunction } from "i18next";

export const getSpecializations = (t: TFunction) => [
  {
    id: "general practice",
    name: t("specializations.general-practice"),
    color: "#E5E5E5",
    icon: "stethoscope",
  },
  {
    id: "pediatrics",
    name: t("specializations.pediatrics"),
    color: "#FFE4B5",
    icon: "child_care",
  },
  {
    id: "cardiology",
    name: t("specializations.cardiology"),
    color: "#FFB6C1",
    icon: "favorite",
  },
  {
    id: "dermatology",
    name: t("specializations.dermatology"),
    color: "#F0FFF0",
    icon: "healing",
  },
  {
    id: "oncology",
    name: t("specializations.oncology"),
    color: "#E6E6FA",
    icon: "coronavirus",
  },
  {
    id: "neurology",
    name: t("specializations.neurology"),
    color: "#ADD8E6",
    icon: "psychology",
  },
  {
    id: "ophthalmology",
    name: t("specializations.ophthalmology"),
    color: "#FFB6C1",
    icon: "visibility",
  },
  {
    id: "orthopedics",
    name: t("specializations.orthopedics"),
    color: "#FFE4C4",
    icon: "accessibility_new",
  },
  {
    id: "psychiatry",
    name: t("specializations.psychiatry"),
    color: "#98FB98",
    icon: "psychology_alt",
  },
  {
    id: "neurosurgery",
    name: t("specializations.neurosurgery"),
    color: "#90EE90",
    icon: "medical_services",
  },
  {
    id: "allergy and immunology",
    name: t("specializations.allergy-and-immunology"),
    color: "#FFB6C1",
    icon: "sick",
  },
  {
    id: "anesthesiology",
    name: t("specializations.anesthesiology"),
    color: "#ADD8E6",
    icon: "mask",
  },
  {
    id: "diagnostic radiology",
    name: t("specializations.diagnostic-radiology"),
    color: "#FFE4B5",
    icon: "biotech",
  },
  {
    id: "emergency medicine",
    name: t("specializations.emergency-medicine"),
    color: "#FFB6C1",
    icon: "local_hospital",
  },
  {
    id: "family medicine",
    name: t("specializations.family-medicine"),
    color: "#E6E6FA",
    icon: "group",
  },
  {
    id: "internal medicine",
    name: t("specializations.internal-medicine"),
    color: "#FFB6C1",
    icon: "medication",
  },
  {
    id: "medical genetics",
    name: t("specializations.medical-genetics"),
    color: "#98FB98",
    icon: "science",
  },
  {
    id: "nuclear medicine",
    name: t("specializations.nuclear-medicine"),
    color: "#ADD8E6",
    icon: "radiology",
  },
  {
    id: "obstetrics and gynecology",
    name: t("specializations.obstetrics-and-gynecology"),
    color: "#90EE90",
    icon: "pregnant_woman",
  },
  {
    id: "pathology",
    name: t("specializations.pathology"),
    color: "#98FB98",
    icon: "microscope",
  },
  {
    id: "rehab",
    name: t("specializations.rehab"),
    color: "#FFE4C4",
    icon: "elderly",
  },
  {
    id: "preventive medicine",
    name: t("specializations.preventive-medicine"),
    color: "#ADD8E6",
    icon: "health_and_safety",
  },
  {
    id: "radiation oncology",
    name: t("specializations.radiation-oncology"),
    color: "#FFE4B5",
    icon: "radiology",
  },
  {
    id: "surgery",
    name: t("specializations.surgery"),
    color: "#FFB6C1",
    icon: "surgical",
  },
  {
    id: "urology",
    name: t("specializations.urology"),
    color: "#E6E6FA",
    icon: "water_drop",
  },
  {
    id: "gastroenterology",
    name: t("specializations.gastroenterology"),
    color: "#FFE4B5",
    icon: "stomach",
  },
];
