import { db } from "@/../firebaseConfig";
import { TextRegular, TextSemiBold } from "@/components/StyledText";
import Colors from "@/constants/Colors";
import { useUserData } from "@/stores/useUserStore";
import { Ionicons } from "@expo/vector-icons";
import DateTimePicker from "@react-native-community/datetimepicker";
import { router, useLocalSearchParams } from "expo-router";
import {
  collection,
  doc,
  getDoc,
  serverTimestamp,
  Timestamp,
  writeBatch,
} from "firebase/firestore";
import { nanoid } from "nanoid";
import React, { useEffect, useState } from "react";
import {
  ActivityIndicator,
  Platform,
  ScrollView,
  TouchableOpacity,
  View,
} from "react-native";
import "react-native-get-random-values";
import { useSafeAreaInsets } from "react-native-safe-area-context";

interface TimeSlot {
  id: string;
  startTime: string;
  endTime: string;
  isAvailable: boolean;
}

const generateTimeSlots = (date: Date): TimeSlot[] => {
  const slots: TimeSlot[] = [];
  const startHour = 9; // 9 AM
  const endHour = 17; // 5 PM
  const interval = 30; // 30 minutes

  for (let hour = startHour; hour < endHour; hour++) {
    for (let minute = 0; minute < 60; minute += interval) {
      const startTime = `${hour.toString().padStart(2, "0")}:${minute
        .toString()
        .padStart(2, "0")}`;
      const endTime = `${hour.toString().padStart(2, "0")}:${(minute + interval)
        .toString()
        .padStart(2, "0")}`;
      slots.push({
        id: `${date.toISOString().split("T")[0]}-${startTime}-${endTime}`,
        startTime,
        endTime,
        isAvailable: true,
      });
    }
  }
  return slots;
};

const formatDate = (date: Date) => {
  return date.toLocaleDateString("en-US", {
    weekday: "long",
    month: "long",
    day: "numeric",
  });
};

const BookingPage = () => {
  const { id } = useLocalSearchParams<{ id: string }>();
  const userData = useUserData();
  const [timeSlots, setTimeSlots] = useState<TimeSlot[]>([]);
  const [selectedSlot, setSelectedSlot] = useState<TimeSlot | null>(null);
  const [doctor, setDoctor] = useState<any>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isBooking, setIsBooking] = useState(false);
  const [selectedDate, setSelectedDate] = useState(new Date());
  const [showDatePicker, setShowDatePicker] = useState(false);
  const insets = useSafeAreaInsets();

  useEffect(() => {
    const fetchDoctorProfile = async () => {
      try {
        const publicProfileRef = doc(db, "publicProfiles", id);
        const docSnap = await getDoc(publicProfileRef);

        if (docSnap.exists()) {
          setDoctor(docSnap.data());
        }
      } catch (err) {
        console.error("Error fetching doctor profile:", err);
      } finally {
        setIsLoading(false);
      }
    };

    if (id) {
      fetchDoctorProfile();
      setTimeSlots(generateTimeSlots(selectedDate));
    }
  }, [id, selectedDate]);

  const onDateChange = (event: any, selectedDate?: Date) => {
    setShowDatePicker(false);
    if (selectedDate) {
      setSelectedDate(selectedDate);
      setSelectedSlot(null);
    }
  };

  const handleBooking = async () => {
    if (!selectedSlot || !doctor || !userData) return;

    try {
      setIsBooking(true);
      const batch = writeBatch(db);

      // Create a new appointment with autogenerated ID
      const appointmentRef = doc(collection(db, "appointments"));
      const appointmentData = {
        doctorId: doctor.uid,
        patientId: userData.uid,
        doctor: {
          firstName: doctor.firstName,
          lastName: doctor.lastName,
        },
        patient: {
          firstName: userData.firstName,
          lastName: userData.lastName,
          image: userData.image || null,
        },
        timeSlot: selectedSlot,
        date: selectedDate,
        price: doctor.consultationPrice,
        status: "pending",
        createdAt: Timestamp.now(),
        scheduledFor: Timestamp.fromDate(
          new Date(
            new Date(selectedDate).setHours(
              parseInt(selectedSlot.startTime.split(":")[0])
            )
          )
        ),
      };
      batch.set(appointmentRef, appointmentData);

      // Create a chat document only if it doesn't already exist
      const chatId = [userData.uid, doctor.uid].sort().join("_");
      const chatRef = doc(db, "chats", chatId);
      const chatSnap = await getDoc(chatRef);

      if (!chatSnap.exists()) {
        batch.set(chatRef, {
          // Users in the chat for querying
          users: [userData.uid, doctor.uid],

          // The doctor and patient details
          participants: {
            doctor: {
              uid: doctor.uid,
              firstName: doctor.firstName,
              lastName: doctor.lastName,
              image: doctor.image || null,
            },
            patient: {
              uid: userData.uid,
              firstName: userData.firstName,
              lastName: userData.lastName,
              image: userData.image || null,
            },
          },

          // Useful for displaying the latest message
          lastMessage: {
            text: "New consultation created",
            senderId: "system",
            timestamp: serverTimestamp(),
          },

          // Chat metadata
          status: "ongoing",
          createdAt: serverTimestamp(),
          updatedAt: serverTimestamp(),
        });
      }

      const messageId = nanoid();
      const messageRef = doc(collection(chatRef, "messages"), messageId);

      // The first message of every new consulation
      batch.set(messageRef, {
        id: messageId,
        text: "New consultation created",
        senderId: "system",
        createdAt: Timestamp.now(),
        system: true,
        sent: false,
        received: false,
        pending: true,
      });

      // Commit batch then navigate to the chat screen
      await batch.commit();
      router.replace(`/protected/${chatId}`);
    } catch (error) {
      console.error("Error booking consultation:", error);
    } finally {
      setIsBooking(false);
    }
  };

  if (isLoading) {
    return (
      <View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
        <ActivityIndicator size="large" color={Colors.primary} />
      </View>
    );
  }

  return (
    <View
      style={{ flex: 1, backgroundColor: "#FFF", paddingBottom: insets.bottom }}
    >
      <ScrollView
        contentContainerStyle={{
          padding: 16,
          gap: 24,
        }}
      >
        {/* Doctor Info */}
        <View
          style={{
            flexDirection: "row",
            gap: 16,
            alignItems: "center",
            paddingBottom: 16,
            borderBottomWidth: 1,
            borderColor: Colors.light.faintGrey,
          }}
        >
          <View style={{ flex: 1 }}>
            <TextSemiBold style={{ fontSize: 20, color: "#000" }}>
              Dr. {doctor?.firstName} {doctor?.lastName}
            </TextSemiBold>
            <TextRegular
              style={{
                fontSize: 14,
                color: "#666",
                marginTop: 4,
              }}
            >
              {doctor?.specializations[0]}
            </TextRegular>
          </View>
          <View>
            <TextSemiBold style={{ fontSize: 20 }}>
              ${doctor?.consultationPrice}
            </TextSemiBold>
            <TextRegular style={{ fontSize: 12, color: "#666" }}>
              per consultation
            </TextRegular>
          </View>
        </View>

        {/* Date Selection */}
        <View>
          <TextSemiBold style={{ fontSize: 16, marginBottom: 12 }}>
            Select Date
          </TextSemiBold>
          <TouchableOpacity
            onPress={() => setShowDatePicker(true)}
            style={{
              flexDirection: "row",
              alignItems: "center",
              justifyContent: "space-between",
              borderWidth: 1,
              borderColor: "#E5E5E5",
              borderRadius: 8,
              padding: 12,
            }}
          >
            <TextRegular style={{ fontSize: 14, color: "#000" }}>
              {formatDate(selectedDate)}
            </TextRegular>
            <Ionicons name="calendar" size={20} color="#666" />
          </TouchableOpacity>
        </View>

        {/* Time Slots */}
        <View>
          <TextSemiBold style={{ fontSize: 16, marginBottom: 16 }}>
            Select a Time Slot
          </TextSemiBold>
          <View
            style={{
              flexDirection: "row",
              flexWrap: "wrap",
              gap: 8,
            }}
          >
            {timeSlots.map((slot) => (
              <TouchableOpacity
                key={slot.id}
                onPress={() => setSelectedSlot(slot)}
                style={{
                  backgroundColor:
                    selectedSlot?.id === slot.id ? "#000" : "#F5F5F5",
                  paddingVertical: 8,
                  paddingHorizontal: 16,
                  borderRadius: 8,
                  borderWidth: 1,
                  borderColor:
                    selectedSlot?.id === slot.id ? "#000" : "#E5E5E5",
                }}
              >
                <TextRegular
                  style={{
                    fontSize: 14,
                    color: selectedSlot?.id === slot.id ? "#FFF" : "#000",
                  }}
                >
                  {slot.startTime} - {slot.endTime}
                </TextRegular>
              </TouchableOpacity>
            ))}
          </View>
        </View>
      </ScrollView>

      {/* Bottom CTA */}
      <View
        style={{
          padding: 16,
          borderTopWidth: 1,
          borderColor: Colors.light.faintGrey,
          backgroundColor: "#fff",
        }}
      >
        <TouchableOpacity
          onPress={handleBooking}
          disabled={!selectedSlot || isBooking}
          style={{
            backgroundColor: selectedSlot ? "#000" : "#E5E5E5",
            paddingVertical: 12,
            borderRadius: 8,
            alignItems: "center",
          }}
        >
          {isBooking ? (
            <ActivityIndicator color="#FFF" />
          ) : (
            <TextSemiBold
              style={{
                color: selectedSlot ? "#FFF" : "#666",
                fontSize: 16,
              }}
            >
              Book Consultation
            </TextSemiBold>
          )}
        </TouchableOpacity>
      </View>

      {showDatePicker && (
        <DateTimePicker
          value={selectedDate}
          mode="date"
          display={Platform.OS === "ios" ? "spinner" : "default"}
          onChange={onDateChange}
          minimumDate={new Date()}
        />
      )}
    </View>
  );
};

export default BookingPage;
